services:
  - type: web
    name: ca-office-tracker
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_USERNAME
        value: your_email@gmail.com
      - key: EMAIL_PASSWORD
        value: your_app_password
